[package]
name = "rusty-psn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.10"
bytesize = "1.1.0"
copypasta = "0.7.1"
sha1_smol = "1.0.0"
serde-xml-rs = "0.5.1"

log = "0.4.16"
simplelog = "0.11.2"

clap = { version = "3.1.8", optional = true, features = ["derive"] }
eframe = { version = "0.17.0", optional = true }
crossterm = { version = "0.23.2", optional = true }

poll-promise = { version = "0.1.0", features = ["tokio"] }
serde = { version = "1.0.136", default-features = false, features = ["derive"] }
tokio = { version = "1.17.0", default-features = false, features = ["rt", "io-util", "macros", "fs"] }

[features]
default = ["egui"]
cli = ["clap", "crossterm"]
egui = ["eframe"]
