name: rusty-psn Builds

on:
  - push
  - pull_request

jobs:
  linux-cli-build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Build rusty-psn (linux-cli)
      run: cargo build --release --no-default-features --features "cli"
    - name: Move binary
      run: |
        mkdir result
        cp target/release/rusty-psn result
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rusty-psn-cli-linux
        path: result

  linux-egui-build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Install egui deps
      run: sudo apt update && sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
    - name: Build rusty-psn (linux-egui)
      run: cargo build --release --no-default-features --features "egui"
    - name: Move binary
      run: |
        mkdir result
        cp target/release/rusty-psn result
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rusty-psn-egui-linux
        path: result
        
  windows-cli-build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Build rusty-psn (windows-egui)
      run: cargo build --release --no-default-features --features "cli"
    - name: Move binary
      run: |
        mkdir result
        copy target/release/rusty-psn.exe result 
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rusty-psn-cli-windows
        path: result 

  windows-egui-build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Rust Cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Build rusty-psn (windows-egui)
      run: cargo build --release --no-default-features --features "egui"
    - name: Move binary
      run: |
        mkdir result
        copy target/release/rusty-psn.exe result 
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rusty-psn-egui-windows
        path: result 
